### ISSUE TITLE
Failed to build TFLite model benchmark tool on windows due to include 'dirent.h'

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#30674]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server 2016 x64
- TensorFlow installed from (source or binary):source
- TensorFlow version:master 
- Bazel version (if compiling from source):0.25
- GCC/Compiler version (if compiling from source):MSVC 14
- CUDA/cuDNN version:not used

**Describe the problem**

Failed to build [TFLite Model Benchmark Tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) with MSVC 14 on windows.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I prepared [the CI environment with Azure DevOps](https://dev.azure.com/mlops/tflite/) to reproduce this error.
I utilized the following script to build TFLite model benchmark tool on windows.

```yaml
variables:
  BAZEL_VERSION: "0.25.2"
  TF_REPOSITORY: https://github.com/tensorflow/tensorflow.git
  TF_NEED_JEMALLOC: 1
  TF_NEED_GCP: 0
  TF_NEED_HDFS: 0
  TF_NEED_AWS: 0
  TF_NEED_KAFKA: 0
  TF_ENABLE_XLA: 0
  TF_NEED_GDR: 0
  TF_NEED_VERBS: 0
  TF_NEED_OPENCL_SYCL: 0
  TF_NEED_OPENCL: 0
  TF_NEED_CUDA: 0
  TF_CUDA_CLANG: 0
  TF_NEED_ROCM: 0
  TF_NEED_MKL: 0
  TF_DOWNLOAD_MKL: 0
  TF_DOWNLOAD_CLANG: 0
  TF_NEED_MPI: 0
  TF_NEED_S3: 0
  TF_SET_ANDROID_WORKSPACE: 0
  TF_NEED_COMPUTECPP: 0
  TF_NEED_TENSORRT: 0
  TF_CONFIGURE_IOS: 0
  - job: build_tflite_win
    pool:
      vmImage: 'vs2017-win2016'
    timeoutInMinutes: 360
    variables:
      BAZEL_SH: "C:\\tools\\msys64\\usr\\bin\\bash.exe"
      BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC"
      CC_OPT_FLAGS: "/arch:AVX /fp:fast"
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x' 
        addToPath: true   
    - powershell: |
        cinst msys2 --params "/NoUpdate" -y --no-progress
        cinst bazel -Version $env:BAZEL_VERSION -y --no-progress -i
        C:\tools\msys64\usr\bin\pacman -S --noconfirm patch unzip
        git clone --branch=$(Build.SourceBranchName) --no-progress --depth=1 $env:TF_REPOSITORY
        $env:PYTHON_BIN_PATH=(Get-Command python).Source
        $env:PYTHON_LIB_PATH="$(python -c 'import site; print(site.getsitepackages()[0])')"
        python ./tensorflow/configure.py
      displayName: 'Install'
    - powershell: |
        cd ./tensorflow
        Set-Item Env:Path "C:\\tools\\msys64\\usr\\bin\\;$Env:Path"
        bazel --output_base $(Build.BinariesDirectory) build -c opt --color=yes --verbose_failures 
 //tensorflow/lite/tools/benchmark:benchmark_model
      condition: succeededOrFailed()
      displayName: 'Build TFLite Model Benchmark Tool'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: tflite_benchmark_win
        targetPath: $(Build.SourcesDirectory)/tensorflow/bazel-bin/tensorflow/lite/tools/benchmark/
      condition: succeeded()
      displayName: 'Publish TFLite Model Benchmark Tool'

```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

All build logs is [uploaded here](https://dev.azure.com/mlops/tflite/_build/results?buildId=147&view=logs&j=e30d995d-3917-5417-8fca-0e6fe874aac5).
This error seems to be caused by 'dirent.h' as follows.

```
  | Execution platform: @bazel_tools//platforms:host_platform |  
  | tensorflow/lite/tools/evaluation/utils.cc(18): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory |  
  | Target //tensorflow/lite/tools/benchmark:benchmark_model failed to build |  
  | INFO: Elapsed time: 4.617s, Critical Path: 3.72s |  
  | INFO: 1 process: 1 local. |  
  | FAILED: Build did NOT complete successfully
```

The POSIX header **'dirent.h' is not part of the C standard and is not portable between platforms.**
Would you like to modify the inclusion?
