### ISSUE TITLE
experimental_connect_to_cluster hangs

### ISSUE THREAD

**Issue by MikeOfZen** [tensorflow/tensorflow#34564]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):No custom code

- TensorFlow installed from (source or binary):Binary
- TensorFlow version (use command below): '2.1.0-dev20191124'
- Python version:3.5.3
- Using GCP image: debian-9-tf-nightly-2-x-v20191124
- Using TPU version: v2-8 , nightly-2.x , preempitble
- zone(probably irrelevent): us-central1-b

*The TPU and Host were built without `ctpu` tool

**Code to reproduce the issue**
```
import tensorflow as tf
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://10.0.101.2:8470')
tf.config.experimental_connect_to_cluster(resolver)
```

**Describe the current behavior**
The `experimental_connect_to_cluster` call hangs indefinitely. 
No error message is produced, it is unclear what should be done.
I had the same problem in 2.0.0.

**Describe the expected behavior**
a.Call shouldn't hang and should provide informative error information
b. If some environment settings need to be set to facilitate TPU-host communications, it should be better documented.

**Other info / logs**
Jupyter log is:
```
[I 22:07:17.299 NotebookApp] Kernel restarted: c9cf10ac-3d03-4a62-a737-3f8e94b44aec
[W 22:07:18.426 NotebookApp] SSL Error on 13 ('79.181.28.67', 59971): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)
[I 22:07:18.935 NotebookApp] Restoring connection for c9cf10ac-3d03-4a62-a737-3f8e94b44aec:c5d1ab723abe433986849772ed497483
[I 22:07:18.935 NotebookApp] Replaying 3 buffered messages
2019-11-24 22:07:31.539205: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-24 22:07:31.546892: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-11-24 22:07:31.547399: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dc09561c30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-11-24 22:07:31.547455: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-11-24 22:07:31.554227: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.101.2:8470}
2019-11-24 22:07:31.554338: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:31900}
[I 22:07:43.819 NotebookApp] Saving file at /project_drive/project/Trainv3.ipynb
[W 22:07:43.820 NotebookApp] Notebook project_drive/project/Trainv3.ipynb is not trusted
```

gcloud compute instances describe host:
```
canIpForward: false                                                                                                                        
cpuPlatform: Intel Haswell                                                                                                                 
creationTimestamp: '2019-11-24T10:28:54.344-08:00'                                                                                         
deletionProtection: false                                                                                                                  
description: ''                                                                                                                            
disks:                                                                                                                                     
- autoDelete: false                                                                                                                        
  boot: true                                                                                                                               
  deviceName: instance-1                                                                                                                   
  guestOsFeatures:                                                                                                                         
  - type: VIRTIO_SCSI_MULTIQUEUE                                                                                                           
  index: 0                                                                                                                                 
  interface: SCSI                                                                                                                          
  kind: compute#attachedDisk                                                                                                               
  licenses:                                                                                                                                
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-9-stretch                                           
  - https://www.googleapis.com/compute/v1/projects/ml-images/global/licenses/debian-tensorflow                                             
  mode: READ_WRITE                                                                                                                         
  source: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/zones/us-central1-b/disks/instance-1                          
  type: PERSISTENT                                                                                                                         
- autoDelete: false                                                                                                                        
  boot: false                                                                                                                              
  deviceName: yaop-project                                                                                                                 
  index: 1                                                                                                                                 
  interface: SCSI                                                                                                                          
  kind: compute#attachedDisk                                                                                                               
  mode: READ_WRITE                                                                                                                         
  source: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/zones/us-central1-b/disks/yaop-project                        
  type: PERSISTENT                                                                                                                         
displayDevice:                                                                                                                             
  enableDisplay: false                                                                                                                     
id: '7023192423693513994'                                                                                                                  
kind: compute#instance                                                                                                                     
labelFingerprint: 42WmSpB8rSM=                                                                                                             
machineType: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/zones/us-central1-b/machineTypes/n1-highmem-4              
metadata:                                                                                                                                  
  fingerprint: oW9kyu6jwEE=                                                                                                                
  kind: compute#metadata                                                                                                                   
name: instance-1                                                                                                                           
networkInterfaces:                                                                                                                         
- accessConfigs:                                                                                                                           
  - kind: compute#accessConfig                                                                                                             
    name: External NAT                                                                                                                     
    natIP: 35.225.64.207                                                                                                                   
    networkTier: PREMIUM                                                                                                                   
    type: ONE_TO_ONE_NAT                                                                                                                   
  fingerprint: VbmPG2_4Dak=                                                                                                                
  kind: compute#networkInterface                                                                                                           
  name: nic0                                                                                                                               
  network: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/global/networks/default                                      
  networkIP: 10.128.0.18                                                                                                                   
  subnetwork: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/regions/us-central1/subnetworks/default                   
reservationAffinity:                                                                                                                       
  consumeReservationType: ANY_RESERVATION                                                                                                  
scheduling:                                                                                                                                
  automaticRestart: true                                                                                                                   
  onHostMaintenance: MIGRATE                                                                                                               
  preemptible: false                                                                                                                       
selfLink: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/zones/us-central1-b/instances/instance-1                      
serviceAccounts:                                                                                                                           
- email: 312164605303-compute@developer.gserviceaccount.com                                                                                
  scopes:                                                                                                                                  
  - https://www.googleapis.com/auth/devstorage.read_only                                                                                   
  - https://www.googleapis.com/auth/logging.write                                                                                          
  - https://www.googleapis.com/auth/monitoring.write                                                                                       
  - https://www.googleapis.com/auth/servicecontrol                                                                                         
  - https://www.googleapis.com/auth/service.management.readonly                                                                            
  - https://www.googleapis.com/auth/trace.append                                                                                           
startRestricted: false                                                                                                                     
status: RUNNING                                                                                                                            
tags:                                                                                                                                      
  fingerprint: Uv7CXg8qQhM=                                                                                                                
  items:                                                                                                                                   
  - http-server                                                                                                                            
  - https-server                                                                                                                           
  - jupyter                                                                                                                                
  - nomachine                                                                                                                              
zone: https://www.googleapis.com/compute/v1/projects/deeplearning-257902/zones/us-central1-b                                               
```
