### ISSUE TITLE
Create tf.substr Op

### ISSUE THREAD

**Issue by samjabrahams** [tensorflow/tensorflow#4232]
Would be useful for a number of purposes, such as extracting data, substring matches (#4009), etc. Proposed API (matches [C++ style substrings](http://www.cplusplus.com/reference/string/string/substr/)):

```
Args:
  inputs: a `Tensor` of type `string`. The strings that will have substrings extracted
  pos: `int32` or `int64` `Tensor`. Position of the first character to be copied as a substring
  len: `int32` or `int64` `Tensor`. Number of characters to include in the substring

Returns:
  A `Tensor` of type `string` containing substrings of `inputs`
```
