### ISSUE TITLE
using tensorflow images in kubernetes got permission denied when accessing a hostpath(PV)

### ISSUE THREAD

**Issue by jokie7585** [tensorflow/tensorflow#42345]
First, i'm sorry for my poor English ( sad

the following is my pod's yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: aNameOfPods
  labels:
    app: tensorflow-runtime
spec:
  restartPolicy: Never
  containers:
    - name: tensorflow-runtime
      image: 'tensorflow/tensorflow:1.8.0'
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
      args:
        - '-c'
        - >-
          cd /catdog;
          ;echo "your application log start below..." > $LogPath;
          sh ./do.sh >> $LogPath 2>&1;
          ;echo "Console diconnected!..." >> $LogPath;done
      volumeMounts:
        - mountPath: /catdog/
          name: data
        - mountPath: /logs/
          name: log
      resources:
        limits:
          nvidia.com/gpu: 0
  volumes:
    - name: data
      hostPath:
        path:  /<hidden>/
        type: Directory
    - name: log
      hostPath:
        path: /<hidden>/
        type: Directory
```

When "cd /catdog;" run, i got an `/bin/sh: 1: ./do.sh: Permission denied`.

But, if I mounting data under `/tmp`, and then `cd /tmp` is works. 

Is there any solution, or it is the point that i should always put my data in `/tmp`?
