### ISSUE TITLE
Problems generating the Hello-World-Project von ESP32

### ISSUE THREAD

**Issue by Jan08** [tensorflow/tensorflow#44346]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linuxmint in VirtualBox
- TensorFlow installed from (source or binary): viva git clone https://github.com/tensorflow/tensorflow.git
- Tensorflow version (commit SHA if source):
- Target platform: ESP32 

**Describe the problem**
Hello guys,

I can't generate projects for ESP32 using make. If  I run:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project

I get:
tensorflow/lite/micro/tools/make/Makefile:418: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:418: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:378: tensorflow/lite/micro/tools/make/targets/esp_makefile.inc: No such file or directory
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/targets/esp_makefile.inc'. Stop.

Maybe this issue is alrady fixed:
https://github.com/tensorflow/tensorflow/pull/44316
If this is so, a big "Thank you!" do the person how did this! 
Where do I get the fixed version? (Sry, I'm new to this topic)

Thank you for all attempts! 

**Please provide the exact sequence of commands/steps when you ran into the problem**
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
after clone git:
git clone https://github.com/tensorflow/tensorflow.git

**Comment by Jan08** [comment]
I tried out the Fix attempted of https://github.com/tensorflow/tensorflow/pull/44316 but it has the same error.

I changed tensorflow/lite/micro/tools/make/targets/esp32_makefile.inc to tensorflow/lite/micro/tools/make/targets/esp_makefile.inc 
annd the containt of the Makefile from:

# Settings for Espressif ESP32

ifeq ($(TARGET), esp)
  TARGET_ARCH := xtensa-esp32
  CCFLAGS := $(filter-out -std=c11,$(CCFLAGS))
  CFLAGS += -std=c11
endif

to:

# Settings for Espressif ESP32


TARGET_ARCH := xtensa-esp32
CCFLAGS := $(filter-out -std=c11,$(CCFLAGS))
CFLAGS += -std=c11

So that doesn't help me. But that file could be the problem, it is defintily named wrong.
Greetings,
Jan

**Comment by Saduf2019** [comment]
@Jan08 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/29524#issuecomment-683521537) and let us know if it helps, a;so please let us know the tf version used.

**Comment by Jan08** [comment]
Hi, 
I followed the Link nur that has no solution...
The Problem is realy Connect to: https://github.com/tensorflow/tensorflow/pull/44316

The Makefile is Named esp32_makefile.inc
Mit esp_makefile.inc,  Like the Error response to.
But simply rename it dont fix the Problem.

Greetings

**Comment by vikramdattu** [comment]
Hello again...

Did you solve your problem?
Update TensorFlow repo to newest and try the build.
It might be that simply picking up the fix doesn't work on some particular commit.

Also, can you please share new logs that you see?

**Comment by jsam589** [comment]
This is still a problem in v2.4.0-rc1 that was just created.  Is a new bug report required to get it fixed in 2.4 before final 2.4 release?  I am manually renaming the .inc file to keep working but prefer it be checked in properly to the repo. Thanks.

**Comment by evaderan-lab** [comment]
Hello, I've just checked with version 2.5.0 and ci_build/test_esp32.sh. I got :
 tensorflow/lite/micro/tools/ci_build/helper_functions.sh: line 31: ./install.sh: No such file or directory
IDF_PATH variable is in fact empty line 36 : 'cd $IDF_PATH'
Notice also that you cannot run the test_esp32.sh twice because the '/tensorflow/lite/micro/tools/ci_build/../../../../../esp-idf
' directory is not removed/cleaned.

**Comment by vikramdattu** [comment]
@evaderan-lab 
Thanks for reporting.

This is something because of `readable_run export ` command not working as expected.
Fixed this with following PR: https://github.com/tensorflow/tensorflow/pull/45334

**Comment by tilakrayal** [comment]
@Jan08,
Related PR #45334 was merged. Could you please take a look at the comments from the developer and the community that the issue got resolved.
 Also please take a look at this [file](https://github.com/silabs-LudvigS/tflite-micro/blob/main/.github/workflows/esp32.yml) for the reference.
```


name: ESP32

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  esp32_daily:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')
    name: ESP32 Continuous Builds
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_esp32.sh

```
