### ISSUE TITLE
Release tensorflow-macos wheel compatible with Python 3.9 and x86

### ISSUE THREAD

**Issue by alexeichhorn** [tensorflow/tensorflow#53583]
Currently in version 2.7.0 of `tensorflow-macos`, there are only 3 wheels released in pip: 2 for arm64 supporting Python 3.8-3.9 and 1 for x86 only supporting Python 3.8.
It would be great to have also a wheel for Python 3.9 for the x86 architecture.
The same thing also applies for `tensorflow-metal`.

**System information**
- TensorFlow version (you are using): 2.7.0

**Describe the feature and the current behavior/state.**
See above

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Every Intel Mac User with Python 3.9

**Any Other info.**

**Comment by mihaimaruseac** [comment]
There are several confusions here.

1. `tensorflow_macos` is intended to work for Apple M1 devices and only those. That is, only for ARM architectures, not x86.
2. `tensorflow_macos` is not released by Google, it is a community build done by people at Apple
3. `tensorflow` is the wheel to use for x86.

**Comment by alexeichhorn** [comment]
Thanks @mihaimaruseac for resolving my confusion. Sorry about that. So then I will ask Apple about `tensorflow-metal` for Python 3.9.

**Comment by colindean** [comment]
Just in case you're like me and find this issue looking for why `tensorflow_macos` does not have an Intel Mac binary wheel package for Python 3.9 (cp39 x86_64), but want a clear(er) resolution method…

You'll want something like this in your `pyproject.toml` for Poetry, or its equivalent in a `requirements.txt`:

```toml
[tool.poetry.dependencies.tensorflow]
version = "2.8.0"
markers = "sys_platform != 'darwin' or (sys_platform == 'darwin' and platform_machine != 'arm64') "

[tool.poetry.dependencies.tensorflow_macos]
version = "2.8.0"
markers = "sys_platform == 'darwin' and platform_machine == 'arm64'"
```

There is a Python 3.8 Intel binary wheel package (cp38) for `tensorflow_macos` but per [this comment](https://github.com/tensorflow/tensorflow/issues/53583#issuecomment-1025017751), it shouldn't be used.

This configuration was tested on a 2022 M1 with macOS 12.2 and a 2018 MBP with macOS 11.6.

_Maximizing for some SEO with word selection because it took me about 10 minutes to find this, so putting  terms I searched for in it…_
