### ISSUE TITLE
tf-nightly: wrong packaging metadata prevents installation using poetry on Linux

### ISSUE THREAD

**Issue by thorbenk** [tensorflow/tensorflow#62928]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf-nightly 2.16.0.dev20240209

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.11.7

### Current behavior?

I cannot install `tf-nightly` using `poetry` on Linux.

I'm getting the following error:

```
$> poetry add tf-nightly
Using version ^2.16.0.dev20240209 for tf-nightly

Updating dependencies
Resolving dependencies... (0.0s)

Package 'tf-nightly' is listed as a dependency of itself.
```

I'm using the following versions:
- Poetry: 1.7.1
- Pip: 24.0
- Python: 3.11.7

It looks to me like the package metadata is wrong:

Quoting from https://pypi.org/pypi/tf-nightly/2.16.0.dev20240209/json ,
the `requires_dist` field contains `tf-nightly ==2.16.0-dev20240209 ; platform_system == "Darwin" and platform_machine == "arm64"'`.

If I understand `poetry`s output correctly, this is the self-dependency that is not allowed.

To reproduce this, just create an empty directory, paste the following as your initial `pyproject.toml`

```toml
[tool.poetry]
name = "tf-package-bug"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

And then run
- `pyenv local 3.11.7` (this is how I'm activating a Python 3.11 installation)
- `python -m pip install poetry` (make sure Poetry is installed for your Python 3.11)
- `poetry install --no-root` (Creates the virtual env using Python 3.11)
- `poetry add tf-nightly` (Throws the error above)

### Standalone code to reproduce the issue

```shell
The steps to reproduce are noted above.
```
