### ISSUE TITLE
misleading comments

### ISSUE THREAD

**Issue by chkap** [tensorflow/tensorflow#8469]
The comments for the function `def _linear(args, output_size, bias, bias_start=0.0):` in tensorflow/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py says:

```
def _linear(args, output_size, bias, bias_start=0.0):
  """Linear map: sum_i(args[i] * W[i]), where W[i] is a variable.
  Args:
    args: a 2D Tensor or a list of 2D, batch x n, Tensors.
    output_size: int, second dimension of W[i].
    bias: boolean, whether to add a bias term or not.
    bias_start: starting value to initialize the bias; 0 by default.
```
However, the function is not implemented as `sum_i(args[i] * W[i])`. 
The key parts in the implementation in line 894-897:
```
    if len(args) == 1:
      res = math_ops.matmul(args[0], weights)
    else:
      res = math_ops.matmul(array_ops.concat(args, 1), weights)
```
The `args` list is firstly concatenated, then `matmul` with the weights tensor. This is totally different from what said in the comments that `Linear map: sum_i(args[i] * W[i]), where W[i] is a variable`. 
So, the comments should probably be rewritten like `Linear map: first, concatenate the args if it is a list, then matmul with a weight tensor`.
